import type { City, PublicListing, Seller } from "./domain";

export const MOCK_SELLERS: Seller[] = [
  {
    id: "flor-carmo",
    name: "Florista do Carmo",
    category: "flowers",
    city: "lisbon",
    privateSalt: "carmo-v2",
    inventory: [
      {
        id: "carmo-seasonal",
        offering: "Seasonal Lisbon bouquet",
        estimatedMarketPriceCents: 3200,
        floorPriceCents: 2600,
        quality: 92,
        marketHeat: 0.68,
        tags: ["romantic", "seasonal", "local", "delivery"],
        attributes: { size: "medium", delivery: true },
      },
      {
        id: "carmo-tulips",
        offering: "Hand-tied Portuguese tulips",
        estimatedMarketPriceCents: 2400,
        floorPriceCents: 1900,
        quality: 84,
        marketHeat: 0.42,
        tags: ["colorful", "local", "pickup"],
        attributes: { stems: 12, delivery: false },
      },
    ],
  },
  {
    id: "bloom-lx",
    name: "Bloom LX",
    category: "flowers",
    city: "lisbon",
    privateSalt: "bloom-v2",
    inventory: [
      {
        id: "bloom-wildflower",
        offering: "Wildflower hand-tied bouquet",
        estimatedMarketPriceCents: 2700,
        floorPriceCents: 2200,
        quality: 86,
        marketHeat: 0.5,
        tags: ["casual", "colorful", "local", "pickup"],
        attributes: { size: "medium", delivery: false },
      },
      {
        id: "bloom-roses",
        offering: "Red rose mini bouquet",
        estimatedMarketPriceCents: 2500,
        floorPriceCents: 2000,
        quality: 82,
        marketHeat: 0.56,
        tags: ["classic", "romantic", "delivery"],
        attributes: { stems: 8, delivery: true },
      },
    ],
  },
  {
    id: "cinema-ideal",
    name: "Cinema Ideal",
    category: "cinema",
    humanPolicy: "one-per-human",
    city: "lisbon",
    privateSalt: "ideal-v2",
    inventory: [
      {
        id: "ideal-d7-d8",
        offering: "Screen 1 · Row D · Seats 7–8",
        estimatedMarketPriceCents: 3400,
        floorPriceCents: 2800,
        quality: 95,
        marketHeat: 0.9,
        tags: ["independent", "central", "evening", "two-seats"],
        attributes: {
          screen: 1,
          row: "D",
          seats: ["7", "8"],
          position: "center",
        },
      },
      {
        id: "ideal-b1-b2",
        offering: "Screen 1 · Row B · Seats 1–2",
        estimatedMarketPriceCents: 2200,
        floorPriceCents: 1600,
        quality: 78,
        marketHeat: 0.34,
        tags: ["independent", "side", "evening", "two-seats"],
        attributes: {
          screen: 1,
          row: "B",
          seats: ["1", "2"],
          position: "far-side",
        },
      },
    ],
  },
  {
    id: "cinema-sao-jorge",
    name: "Cinema São Jorge",
    category: "cinema",
    humanPolicy: "one-per-human",
    city: "lisbon",
    privateSalt: "jorge-v2",
    inventory: [
      {
        id: "jorge-balcony-b9-b10",
        offering: "Balcony · Row B · Seats 9–10",
        estimatedMarketPriceCents: 3600,
        floorPriceCents: 3000,
        quality: 97,
        marketHeat: 0.96,
        tags: ["classic", "central", "balcony", "evening", "two-seats"],
        attributes: {
          section: "balcony",
          row: "B",
          seats: ["9", "10"],
          position: "center",
        },
      },
      {
        id: "jorge-stalls-j12-j13",
        offering: "Stalls · Row J · Seats 12–13",
        estimatedMarketPriceCents: 2700,
        floorPriceCents: 2100,
        quality: 86,
        marketHeat: 0.55,
        tags: ["classic", "rear", "evening", "two-seats"],
        attributes: {
          section: "stalls",
          row: "J",
          seats: ["12", "13"],
          position: "rear-center",
        },
      },
    ],
  },
  {
    id: "cinemateca",
    name: "Cinemateca Portuguesa",
    category: "cinema",
    humanPolicy: "one-per-human",
    city: "lisbon",
    privateSalt: "cinemateca-v2",
    inventory: [
      {
        id: "cinemateca-e6-e7",
        offering: "Main room · Row E · Seats 6–7",
        estimatedMarketPriceCents: 2800,
        floorPriceCents: 2200,
        quality: 90,
        marketHeat: 0.62,
        tags: ["arthouse", "central", "quiet", "evening", "two-seats"],
        attributes: {
          room: "main",
          row: "E",
          seats: ["6", "7"],
          position: "center",
        },
      },
      {
        id: "cinemateca-a1-a2",
        offering: "Main room · Row A · Seats 1–2",
        estimatedMarketPriceCents: 1800,
        floorPriceCents: 1300,
        quality: 74,
        marketHeat: 0.25,
        tags: ["arthouse", "front", "side", "evening", "two-seats"],
        attributes: {
          room: "main",
          row: "A",
          seats: ["1", "2"],
          position: "front-side",
        },
      },
    ],
  },
  {
    id: "prado",
    name: "Prado",
    category: "dinner",
    humanPolicy: "one-per-human",
    city: "lisbon",
    privateSalt: "prado-v2",
    inventory: [
      {
        id: "prado-window-2030",
        offering: "Window table for two · 20:30",
        estimatedMarketPriceCents: 11200,
        floorPriceCents: 9300,
        quality: 96,
        marketHeat: 0.86,
        tags: ["romantic", "seasonal", "quiet", "central", "window"],
        attributes: { partySize: 2, time: "20:30", table: "window" },
      },
      {
        id: "prado-counter-1900",
        offering: "Counter seats for two · 19:00",
        estimatedMarketPriceCents: 8800,
        floorPriceCents: 7200,
        quality: 88,
        marketHeat: 0.5,
        tags: ["seasonal", "central", "early", "counter"],
        attributes: { partySize: 2, time: "19:00", table: "counter" },
      },
    ],
  },
  {
    id: "taberna-lx",
    name: "Taberna LX",
    category: "dinner",
    humanPolicy: "one-per-human",
    city: "lisbon",
    privateSalt: "taberna-v2",
    inventory: [
      {
        id: "taberna-table-2030",
        offering: "Portuguese dinner table for two · 20:30",
        estimatedMarketPriceCents: 8200,
        floorPriceCents: 6900,
        quality: 87,
        marketHeat: 0.66,
        tags: ["local", "lively", "traditional", "central"],
        attributes: { partySize: 2, time: "20:30", table: "standard" },
      },
    ],
  },
  {
    id: "miradouro-table",
    name: "Miradouro Table",
    category: "dinner",
    humanPolicy: "one-per-human",
    city: "lisbon",
    privateSalt: "miradouro-v2",
    inventory: [
      {
        id: "miradouro-sunset-1930",
        offering: "Sunset tasting table for two · 19:30",
        estimatedMarketPriceCents: 12800,
        floorPriceCents: 10800,
        quality: 94,
        marketHeat: 0.92,
        tags: ["romantic", "view", "sunset", "tasting-menu"],
        attributes: { partySize: 2, time: "19:30", table: "terrace" },
      },
    ],
  },
  {
    id: "lisbon-cab",
    name: "Lisbon Cab Co.",
    category: "transport",
    city: "lisbon",
    privateSalt: "cab-v2",
    inventory: [
      {
        id: "cab-two-transfers",
        offering: "Two private transfers within central Lisbon",
        estimatedMarketPriceCents: 2800,
        floorPriceCents: 2200,
        quality: 85,
        marketHeat: 0.48,
        tags: ["private", "door-to-door", "evening"],
        attributes: { rides: 2, vehicle: "sedan" },
      },
    ],
  },
  {
    id: "eco-ride",
    name: "Eco Ride Lisboa",
    category: "transport",
    city: "lisbon",
    privateSalt: "eco-v2",
    inventory: [
      {
        id: "eco-evening-credit",
        offering: "Electric evening ride credit",
        estimatedMarketPriceCents: 2200,
        floorPriceCents: 1700,
        quality: 82,
        marketHeat: 0.4,
        tags: ["electric", "flexible", "evening"],
        attributes: { rides: 2, vehicle: "electric" },
      },
    ],
  },
  {
    id: "tejo-sunset",
    name: "Tejo Sunset",
    category: "experience",
    humanPolicy: "one-per-human",
    city: "lisbon",
    privateSalt: "tejo-v2",
    inventory: [
      {
        id: "tejo-deck-two",
        offering: "Two-person sunset river cruise · upper deck",
        estimatedMarketPriceCents: 7600,
        floorPriceCents: 6300,
        quality: 91,
        marketHeat: 0.79,
        tags: ["romantic", "sunset", "river", "two-seats"],
        attributes: { partySize: 2, section: "upper-deck" },
      },
    ],
  },
  {
    id: "tile-workshop",
    name: "Azulejo Atelier",
    category: "experience",
    humanPolicy: "one-per-human",
    city: "lisbon",
    privateSalt: "azulejo-v2",
    inventory: [
      {
        id: "tile-private-two",
        offering: "Private tile-painting session for two",
        estimatedMarketPriceCents: 6800,
        floorPriceCents: 5600,
        quality: 88,
        marketHeat: 0.52,
        tags: ["creative", "private", "local", "two-seats"],
        attributes: { partySize: 2, durationMinutes: 90 },
      },
    ],
  },
  {
    id: "san-siro",
    name: "San Siro Stadium",
    category: "experience",
    humanPolicy: "one-per-human",
    city: "milan",
    privateSalt: "sansiro-v2",
    inventory: [
      {
        id: "san-siro-home-match",
        offering: "Two tickets to an AC Milan home match",
        estimatedMarketPriceCents: 9500,
        floorPriceCents: 7800,
        quality: 95,
        marketHeat: 0.9,
        tags: ["football", "match", "stadium", "two-seats", "evening"],
        attributes: { partySize: 2, venue: "San Siro", section: "standard" },
      },
    ],
  },
  {
    id: "duomo-rooftop",
    name: "Duomo Rooftop Tour",
    category: "experience",
    humanPolicy: "one-per-human",
    city: "milan",
    privateSalt: "duomo-v2",
    inventory: [
      {
        id: "duomo-sunset-two",
        offering: "Sunset rooftop tour for two",
        estimatedMarketPriceCents: 4200,
        floorPriceCents: 3400,
        quality: 87,
        marketHeat: 0.64,
        tags: ["view", "landmark", "sunset", "two-seats"],
        attributes: { partySize: 2, time: "sunset", venue: "Duomo" },
      },
    ],
  },
  {
    id: "osteria-brera",
    name: "Osteria di Brera",
    category: "dinner",
    humanPolicy: "one-per-human",
    city: "milan",
    privateSalt: "brera-v2",
    inventory: [
      {
        id: "brera-seasonal-2030",
        offering: "Seasonal dinner table for two · 20:30",
        estimatedMarketPriceCents: 12400,
        floorPriceCents: 10400,
        quality: 94,
        marketHeat: 0.82,
        tags: ["romantic", "seasonal", "quiet", "central"],
        attributes: { partySize: 2, time: "20:30", district: "Brera" },
      },
    ],
  },
  {
    id: "trattoria-navigli",
    name: "Trattoria dei Navigli",
    category: "dinner",
    humanPolicy: "one-per-human",
    city: "milan",
    privateSalt: "navigli-v2",
    inventory: [
      {
        id: "navigli-table-2100",
        offering: "Milanese dinner table for two · 21:00",
        estimatedMarketPriceCents: 9800,
        floorPriceCents: 8200,
        quality: 91,
        marketHeat: 0.73,
        tags: ["traditional", "canal-side", "romantic", "lively"],
        attributes: { partySize: 2, time: "21:00", district: "Navigli" },
      },
    ],
  },
  {
    id: "risotteria-monza",
    name: "Risotteria Monza",
    category: "dinner",
    humanPolicy: "one-per-human",
    city: "milan",
    privateSalt: "monza-v2",
    inventory: [
      {
        id: "monza-tasting-two",
        offering: "Risotto tasting for two",
        estimatedMarketPriceCents: 7600,
        floorPriceCents: 6300,
        quality: 86,
        marketHeat: 0.5,
        tags: ["local", "cozy", "traditional"],
        attributes: { partySize: 2, menu: "tasting" },
      },
    ],
  },
  {
    id: "milano-taxi",
    name: "Milano Taxi Co.",
    category: "transport",
    city: "milan",
    privateSalt: "milanotaxi-v2",
    inventory: [
      {
        id: "milano-two-transfers",
        offering: "Two private transfers across Milan",
        estimatedMarketPriceCents: 3000,
        floorPriceCents: 2400,
        quality: 84,
        marketHeat: 0.55,
        tags: ["private", "door-to-door", "evening", "stadium"],
        attributes: { rides: 2, vehicle: "sedan" },
      },
    ],
  },
  {
    id: "atm-passes",
    name: "ATM Day Passes",
    category: "transport",
    city: "milan",
    privateSalt: "atm-v2",
    inventory: [
      {
        id: "atm-two-day-passes",
        offering: "Two Milan metro day passes",
        estimatedMarketPriceCents: 1400,
        floorPriceCents: 1100,
        quality: 78,
        marketHeat: 0.38,
        tags: ["public", "flexible", "cheap"],
        attributes: { passengers: 2, duration: "one-day" },
      },
    ],
  },
  {
    id: "cinema-anteo",
    name: "Cinema Anteo",
    category: "cinema",
    humanPolicy: "one-per-human",
    city: "milan",
    privateSalt: "anteo-v2",
    inventory: [
      {
        id: "anteo-e8-e9",
        offering: "Main screen · Row E · Seats 8–9",
        estimatedMarketPriceCents: 2800,
        floorPriceCents: 2300,
        quality: 88,
        marketHeat: 0.58,
        tags: ["arthouse", "central", "evening", "two-seats"],
        attributes: {
          screen: "main",
          row: "E",
          seats: ["8", "9"],
          position: "center",
        },
      },
    ],
  },
  {
    id: "fioraio-brera",
    name: "Fioraio di Brera",
    category: "flowers",
    city: "milan",
    privateSalt: "fioraio-v2",
    inventory: [
      {
        id: "brera-hand-tied",
        offering: "Hand-tied seasonal bouquet",
        estimatedMarketPriceCents: 3000,
        floorPriceCents: 2500,
        quality: 85,
        marketHeat: 0.54,
        tags: ["romantic", "local", "delivery"],
        attributes: { size: "medium", delivery: true },
      },
    ],
  },
  {
    id: "ginza-kappo",
    name: "Ginza Kappo Hana",
    category: "dinner",
    humanPolicy: "one-per-human",
    city: "tokyo",
    privateSalt: "ginza-kappo-v1",
    inventory: [
      {
        id: "kappo-counter-1930",
        offering: "Kaiseki counter for two · 19:30",
        estimatedMarketPriceCents: 13800,
        floorPriceCents: 11400,
        quality: 96,
        marketHeat: 0.85,
        tags: ["kaiseki", "omakase", "quiet", "counter"],
        attributes: { partySize: 2, time: "19:30" },
      },
      {
        id: "kappo-tatami-2100",
        offering: "Tatami room for two · 21:00",
        estimatedMarketPriceCents: 11800,
        floorPriceCents: 9600,
        quality: 90,
        marketHeat: 0.55,
        tags: ["kaiseki", "private", "late"],
        attributes: { partySize: 2, time: "21:00" },
      },
    ],
  },
  {
    id: "toho-shinjuku",
    name: "Toho Cinema Shinjuku",
    category: "cinema",
    humanPolicy: "one-per-human",
    city: "tokyo",
    privateSalt: "toho-shinjuku-v1",
    inventory: [
      {
        id: "toho-imax-e",
        offering: "IMAX · Row E · Seats 10–11",
        estimatedMarketPriceCents: 3200,
        floorPriceCents: 2500,
        quality: 91,
        marketHeat: 0.75,
        tags: ["imax", "central", "evening", "two-seats"],
        attributes: { row: "E", seats: "10-11" },
      },
      {
        id: "toho-std-j",
        offering: "Screen 3 · Row J · Seats 4–5",
        estimatedMarketPriceCents: 2000,
        floorPriceCents: 1500,
        quality: 82,
        marketHeat: 0.4,
        tags: ["evening", "two-seats"],
        attributes: { row: "J", seats: "4-5" },
      },
    ],
  },
  {
    id: "tokyo-dome",
    name: "Tokyo Dome Baseball",
    category: "experience",
    humanPolicy: "one-per-human",
    city: "tokyo",
    privateSalt: "tokyo-dome-v1",
    inventory: [
      {
        id: "dome-infield-a",
        offering: "Giants game · Infield A · Pair",
        estimatedMarketPriceCents: 9800,
        floorPriceCents: 7800,
        quality: 95,
        marketHeat: 0.9,
        tags: ["baseball", "game", "two-seats", "infield"],
        attributes: { section: "Infield A", pair: true },
      },
      {
        id: "dome-outfield",
        offering: "Giants game · Outfield · Pair",
        estimatedMarketPriceCents: 5400,
        floorPriceCents: 4200,
        quality: 84,
        marketHeat: 0.6,
        tags: ["baseball", "game", "two-seats", "outfield"],
        attributes: { section: "Outfield", pair: true },
      },
    ],
  },
  {
    id: "tokyo-metro",
    name: "Tokyo Metro Passes",
    category: "transport",
    city: "tokyo",
    privateSalt: "tokyo-metro-v1",
    inventory: [
      {
        id: "metro-day-pair",
        offering: "Two 24h metro passes",
        estimatedMarketPriceCents: 1600,
        floorPriceCents: 1200,
        quality: 80,
        marketHeat: 0.3,
        tags: ["public", "flexible", "cheap"],
        attributes: { passes: 2 },
      },
    ],
  },
  {
    id: "hanayoshi",
    name: "Hanayoshi Ginza",
    category: "flowers",
    city: "tokyo",
    privateSalt: "hanayoshi-v1",
    inventory: [
      {
        id: "hana-seasonal",
        offering: "Seasonal ikebana bouquet",
        estimatedMarketPriceCents: 3400,
        floorPriceCents: 2700,
        quality: 89,
        marketHeat: 0.45,
        tags: ["seasonal", "elegant", "delivery"],
        attributes: { style: "ikebana" },
      },
    ],
  },
  {
    id: "bandra-masala",
    name: "Bandra Masala House",
    category: "dinner",
    humanPolicy: "one-per-human",
    city: "mumbai",
    privateSalt: "bandra-masala-v1",
    inventory: [
      {
        id: "masala-terrace-2030",
        offering: "Terrace table for two · 20:30",
        estimatedMarketPriceCents: 6800,
        floorPriceCents: 5400,
        quality: 92,
        marketHeat: 0.8,
        tags: ["terrace", "lively", "local", "spice"],
        attributes: { partySize: 2, time: "20:30" },
      },
      {
        id: "masala-indoor-1900",
        offering: "Indoor table for two · 19:00",
        estimatedMarketPriceCents: 5200,
        floorPriceCents: 4100,
        quality: 85,
        marketHeat: 0.5,
        tags: ["local", "early", "family"],
        attributes: { partySize: 2, time: "19:00" },
      },
    ],
  },
  {
    id: "regal-colaba",
    name: "Regal Cinema Colaba",
    category: "cinema",
    humanPolicy: "one-per-human",
    city: "mumbai",
    privateSalt: "regal-colaba-v1",
    inventory: [
      {
        id: "regal-balcony-c",
        offering: "Balcony · Row C · Seats 7–8",
        estimatedMarketPriceCents: 1800,
        floorPriceCents: 1300,
        quality: 87,
        marketHeat: 0.65,
        tags: ["heritage", "balcony", "evening", "two-seats"],
        attributes: { row: "C", seats: "7-8" },
      },
    ],
  },
  {
    id: "wankhede",
    name: "Wankhede Cricket Stands",
    category: "experience",
    humanPolicy: "one-per-human",
    city: "mumbai",
    privateSalt: "wankhede-v1",
    inventory: [
      {
        id: "wankhede-north",
        offering: "T20 match · North Stand · Pair",
        estimatedMarketPriceCents: 8800,
        floorPriceCents: 7000,
        quality: 94,
        marketHeat: 0.9,
        tags: ["cricket", "match", "two-seats", "stand"],
        attributes: { stand: "North", pair: true },
      },
    ],
  },
  {
    id: "kaali-peeli",
    name: "Kaali-Peeli Cabs",
    category: "transport",
    city: "mumbai",
    privateSalt: "kaali-peeli-v1",
    inventory: [
      {
        id: "kp-evening",
        offering: "Two classic taxi transfers",
        estimatedMarketPriceCents: 1400,
        floorPriceCents: 1000,
        quality: 79,
        marketHeat: 0.35,
        tags: ["classic", "door-to-door", "evening"],
        attributes: { rides: 2 },
      },
    ],
  },
  {
    id: "dadar-flowers",
    name: "Dadar Flower Market",
    category: "flowers",
    city: "mumbai",
    privateSalt: "dadar-flowers-v1",
    inventory: [
      {
        id: "dadar-marigold",
        offering: "Marigold and jasmine garland set",
        estimatedMarketPriceCents: 1600,
        floorPriceCents: 1100,
        quality: 83,
        marketHeat: 0.4,
        tags: ["traditional", "fragrant", "local"],
        attributes: { style: "garland" },
      },
    ],
  },
  {
    id: "greenwich-trattoria",
    name: "Greenwich Trattoria",
    category: "dinner",
    humanPolicy: "one-per-human",
    city: "newyork",
    privateSalt: "greenwich-trattoria-v1",
    inventory: [
      {
        id: "gt-garden-2000",
        offering: "Garden table for two · 20:00",
        estimatedMarketPriceCents: 14800,
        floorPriceCents: 12200,
        quality: 93,
        marketHeat: 0.85,
        tags: ["romantic", "garden", "village"],
        attributes: { partySize: 2, time: "20:00" },
      },
      {
        id: "gt-bar-1830",
        offering: "Bar seats for two · 18:30",
        estimatedMarketPriceCents: 9800,
        floorPriceCents: 7900,
        quality: 84,
        marketHeat: 0.5,
        tags: ["casual", "early", "bar"],
        attributes: { partySize: 2, time: "18:30" },
      },
    ],
  },
  {
    id: "angelika",
    name: "Angelika Film Center",
    category: "cinema",
    humanPolicy: "one-per-human",
    city: "newyork",
    privateSalt: "angelika-v1",
    inventory: [
      {
        id: "angelika-d",
        offering: "Screen 1 · Row D · Seats 5–6",
        estimatedMarketPriceCents: 3600,
        floorPriceCents: 2800,
        quality: 90,
        marketHeat: 0.7,
        tags: ["arthouse", "central", "evening", "two-seats"],
        attributes: { row: "D", seats: "5-6" },
      },
    ],
  },
  {
    id: "yankee-bleachers",
    name: "Yankee Stadium Bleachers",
    category: "experience",
    humanPolicy: "one-per-human",
    city: "newyork",
    privateSalt: "yankee-bleachers-v1",
    inventory: [
      {
        id: "yankees-203",
        offering: "Yankees game · Section 203 · Pair",
        estimatedMarketPriceCents: 10800,
        floorPriceCents: 8600,
        quality: 95,
        marketHeat: 0.9,
        tags: ["baseball", "game", "two-seats", "bleachers"],
        attributes: { section: "203", pair: true },
      },
    ],
  },
  {
    id: "nyc-cab",
    name: "NYC Yellow Cab",
    category: "transport",
    city: "newyork",
    privateSalt: "nyc-cab-v1",
    inventory: [
      {
        id: "nyc-rides",
        offering: "Two yellow cab transfers",
        estimatedMarketPriceCents: 2600,
        floorPriceCents: 2000,
        quality: 81,
        marketHeat: 0.4,
        tags: ["classic", "door-to-door", "evening"],
        attributes: { rides: 2 },
      },
    ],
  },
  {
    id: "chelsea-flowers",
    name: "Chelsea Flower Studio",
    category: "flowers",
    city: "newyork",
    privateSalt: "chelsea-flowers-v1",
    inventory: [
      {
        id: "chelsea-peony",
        offering: "Peony hand-tied bouquet",
        estimatedMarketPriceCents: 4200,
        floorPriceCents: 3300,
        quality: 88,
        marketHeat: 0.5,
        tags: ["romantic", "seasonal", "delivery"],
        attributes: { style: "hand-tied" },
      },
    ],
  },
];

export function toPublicListing(
  seller: Seller,
  item: Seller["inventory"][number],
): PublicListing {
  return {
    id: item.id,
    sellerId: seller.id,
    sellerName: seller.name,
    city: seller.city,
    category: seller.category,
    offering: item.offering,
    estimatedMarketPriceCents: item.estimatedMarketPriceCents,
    quality: item.quality,
    tags: [...item.tags],
    attributes: structuredClone(item.attributes),
  };
}

export function publicCatalogForPlanner(): PublicListing[] {
  return MOCK_SELLERS.flatMap((seller) =>
    seller.inventory.map((item) => toPublicListing(seller, item)),
  );
}

const CITY_MATCHERS: Array<[City, RegExp]> = [
  ["lisbon", /\blisbo[an]\b/i],
  ["milan", /\bmilan(?:o)?\b/i],
  ["tokyo", /\btokyo\b/i],
  ["mumbai", /\bmumbai\b|\bbombay\b/i],
  ["newyork", /\bnew\s*york\b|\bnyc\b|\bmanhattan\b/i],
];

export const CITY_LABELS: Record<City, string> = {
  lisbon: "Lisbon",
  milan: "Milan",
  tokyo: "Tokyo",
  mumbai: "Mumbai",
  newyork: "New York",
};

export class UnknownCityError extends Error {
  readonly available: string[];
  constructor(location: string) {
    const available = Object.values(CITY_LABELS);
    super(
      `No sellers found in "${location}" yet. Cities with sellers: ${available.join(", ")}. Please retry your intent with one of these.`,
    );
    this.name = "UnknownCityError";
    this.available = available;
  }
}

export function cityForLocation(location: string): City | null {
  for (const [city, matcher] of CITY_MATCHERS) {
    if (matcher.test(location)) return city;
  }
  return null;
}

export function sellersForLocation(location: string): Seller[] {
  const city = cityForLocation(location);
  if (!city) throw new UnknownCityError(location);
  return MOCK_SELLERS.filter((seller) => seller.city === city);
}
