import type { Seller } from "./domain.js";

export const MOCK_SELLERS: Seller[] = [
  {
    id: "flor-carmo",
    name: "Florista do Carmo",
    category: "flowers",
    offering: "Seasonal Lisbon bouquet",
    listPriceCents: 3200,
    reservePriceCents: 2600,
    quality: 92,
    tags: ["romantic", "seasonal", "local", "delivery"],
    privateSalt: "carmo-v1",
  },
  {
    id: "bloom-lx",
    name: "Bloom LX",
    category: "flowers",
    offering: "Wildflower hand-tied bouquet",
    listPriceCents: 2700,
    reservePriceCents: 2200,
    quality: 86,
    tags: ["casual", "colorful", "local", "pickup"],
    privateSalt: "bloom-v1",
  },
  {
    id: "alfama-petals",
    name: "Alfama Petals",
    category: "flowers",
    offering: "Red rose mini bouquet",
    listPriceCents: 2400,
    reservePriceCents: 2000,
    quality: 81,
    tags: ["classic", "romantic", "delivery"],
    privateSalt: "alfama-v1",
  },
  {
    id: "cinema-ideal",
    name: "Cinema Ideal",
    category: "cinema",
    offering: "Two evening film tickets",
    listPriceCents: 2600,
    reservePriceCents: 2200,
    quality: 89,
    tags: ["independent", "central", "evening", "two-seats"],
    privateSalt: "ideal-v1",
  },
  {
    id: "cinema-sao-jorge",
    name: "Cinema São Jorge",
    category: "cinema",
    offering: "Two balcony film tickets",
    listPriceCents: 3000,
    reservePriceCents: 2400,
    quality: 93,
    tags: ["classic", "central", "evening", "two-seats"],
    privateSalt: "jorge-v1",
  },
  {
    id: "cinemateca",
    name: "Cinemateca Portuguesa",
    category: "cinema",
    offering: "Two repertory screening tickets",
    listPriceCents: 1800,
    reservePriceCents: 1400,
    quality: 84,
    tags: ["arthouse", "quiet", "evening", "two-seats"],
    privateSalt: "cinemateca-v1",
  },
  {
    id: "prado",
    name: "Prado",
    category: "dinner",
    offering: "Dinner for two with shared plates",
    listPriceCents: 11200,
    reservePriceCents: 9300,
    quality: 96,
    tags: ["romantic", "seasonal", "quiet", "central"],
    privateSalt: "prado-v1",
  },
  {
    id: "taberna-lx",
    name: "Taberna LX",
    category: "dinner",
    offering: "Portuguese dinner for two",
    listPriceCents: 8200,
    reservePriceCents: 6900,
    quality: 87,
    tags: ["local", "lively", "traditional", "central"],
    privateSalt: "taberna-v1",
  },
  {
    id: "miradouro-table",
    name: "Miradouro Table",
    category: "dinner",
    offering: "Sunset tasting menu for two",
    listPriceCents: 12800,
    reservePriceCents: 10800,
    quality: 94,
    tags: ["romantic", "view", "sunset", "tasting-menu"],
    privateSalt: "miradouro-v1",
  },
  {
    id: "lisbon-cab",
    name: "Lisbon Cab Co.",
    category: "transport",
    offering: "Two private transfers within central Lisbon",
    listPriceCents: 2800,
    reservePriceCents: 2200,
    quality: 85,
    tags: ["private", "door-to-door", "evening"],
    privateSalt: "cab-v1",
  },
  {
    id: "eco-ride",
    name: "Eco Ride Lisboa",
    category: "transport",
    offering: "Electric ride credit",
    listPriceCents: 2200,
    reservePriceCents: 1700,
    quality: 82,
    tags: ["electric", "flexible", "evening"],
    privateSalt: "eco-v1",
  },
  {
    id: "tejo-sunset",
    name: "Tejo Sunset",
    category: "experience",
    offering: "Two-person sunset river cruise",
    listPriceCents: 7600,
    reservePriceCents: 6300,
    quality: 91,
    tags: ["romantic", "sunset", "river", "two-seats"],
    privateSalt: "tejo-v1",
  },
  {
    id: "tile-workshop",
    name: "Azulejo Atelier",
    category: "experience",
    offering: "Private tile-painting session for two",
    listPriceCents: 6800,
    reservePriceCents: 5600,
    quality: 88,
    tags: ["creative", "private", "local", "two-seats"],
    privateSalt: "azulejo-v1",
  },
];

export function publicCatalogForPlanner() {
  return MOCK_SELLERS.map(
    ({ privateSalt: _privateSalt, reservePriceCents: _reserve, ...publicSeller }) =>
      publicSeller,
  );
}
