import type { PublicListing, Seller } from "./domain";

export const MOCK_SELLERS: Seller[] = [
  {
    id: "flor-carmo",
    name: "Florista do Carmo",
    category: "flowers",
    privateSalt: "carmo-v2",
    inventory: [
      {
        id: "carmo-seasonal",
        offering: "Seasonal Lisbon bouquet",
        estimatedMarketPriceCents: 3200,
        floorPriceCents: 2600,
        quality: 92,
        marketHeat: 0.68,
        tags: ["romantic", "seasonal", "local", "delivery"],
        attributes: { size: "medium", delivery: true },
      },
      {
        id: "carmo-tulips",
        offering: "Hand-tied Portuguese tulips",
        estimatedMarketPriceCents: 2400,
        floorPriceCents: 1900,
        quality: 84,
        marketHeat: 0.42,
        tags: ["colorful", "local", "pickup"],
        attributes: { stems: 12, delivery: false },
      },
    ],
  },
  {
    id: "bloom-lx",
    name: "Bloom LX",
    category: "flowers",
    privateSalt: "bloom-v2",
    inventory: [
      {
        id: "bloom-wildflower",
        offering: "Wildflower hand-tied bouquet",
        estimatedMarketPriceCents: 2700,
        floorPriceCents: 2200,
        quality: 86,
        marketHeat: 0.5,
        tags: ["casual", "colorful", "local", "pickup"],
        attributes: { size: "medium", delivery: false },
      },
      {
        id: "bloom-roses",
        offering: "Red rose mini bouquet",
        estimatedMarketPriceCents: 2500,
        floorPriceCents: 2000,
        quality: 82,
        marketHeat: 0.56,
        tags: ["classic", "romantic", "delivery"],
        attributes: { stems: 8, delivery: true },
      },
    ],
  },
  {
    id: "cinema-ideal",
    name: "Cinema Ideal",
    category: "cinema",
    privateSalt: "ideal-v2",
    inventory: [
      {
        id: "ideal-d7-d8",
        offering: "Screen 1 · Row D · Seats 7–8",
        estimatedMarketPriceCents: 3400,
        floorPriceCents: 2800,
        quality: 95,
        marketHeat: 0.9,
        tags: ["independent", "central", "evening", "two-seats"],
        attributes: {
          screen: 1,
          row: "D",
          seats: ["7", "8"],
          position: "center",
        },
      },
      {
        id: "ideal-b1-b2",
        offering: "Screen 1 · Row B · Seats 1–2",
        estimatedMarketPriceCents: 2200,
        floorPriceCents: 1600,
        quality: 78,
        marketHeat: 0.34,
        tags: ["independent", "side", "evening", "two-seats"],
        attributes: {
          screen: 1,
          row: "B",
          seats: ["1", "2"],
          position: "far-side",
        },
      },
    ],
  },
  {
    id: "cinema-sao-jorge",
    name: "Cinema São Jorge",
    category: "cinema",
    privateSalt: "jorge-v2",
    inventory: [
      {
        id: "jorge-balcony-b9-b10",
        offering: "Balcony · Row B · Seats 9–10",
        estimatedMarketPriceCents: 3600,
        floorPriceCents: 3000,
        quality: 97,
        marketHeat: 0.96,
        tags: ["classic", "central", "balcony", "evening", "two-seats"],
        attributes: {
          section: "balcony",
          row: "B",
          seats: ["9", "10"],
          position: "center",
        },
      },
      {
        id: "jorge-stalls-j12-j13",
        offering: "Stalls · Row J · Seats 12–13",
        estimatedMarketPriceCents: 2700,
        floorPriceCents: 2100,
        quality: 86,
        marketHeat: 0.55,
        tags: ["classic", "rear", "evening", "two-seats"],
        attributes: {
          section: "stalls",
          row: "J",
          seats: ["12", "13"],
          position: "rear-center",
        },
      },
    ],
  },
  {
    id: "cinemateca",
    name: "Cinemateca Portuguesa",
    category: "cinema",
    privateSalt: "cinemateca-v2",
    inventory: [
      {
        id: "cinemateca-e6-e7",
        offering: "Main room · Row E · Seats 6–7",
        estimatedMarketPriceCents: 2800,
        floorPriceCents: 2200,
        quality: 90,
        marketHeat: 0.62,
        tags: ["arthouse", "central", "quiet", "evening", "two-seats"],
        attributes: {
          room: "main",
          row: "E",
          seats: ["6", "7"],
          position: "center",
        },
      },
      {
        id: "cinemateca-a1-a2",
        offering: "Main room · Row A · Seats 1–2",
        estimatedMarketPriceCents: 1800,
        floorPriceCents: 1300,
        quality: 74,
        marketHeat: 0.25,
        tags: ["arthouse", "front", "side", "evening", "two-seats"],
        attributes: {
          room: "main",
          row: "A",
          seats: ["1", "2"],
          position: "front-side",
        },
      },
    ],
  },
  {
    id: "prado",
    name: "Prado",
    category: "dinner",
    privateSalt: "prado-v2",
    inventory: [
      {
        id: "prado-window-2030",
        offering: "Window table for two · 20:30",
        estimatedMarketPriceCents: 11200,
        floorPriceCents: 9300,
        quality: 96,
        marketHeat: 0.86,
        tags: ["romantic", "seasonal", "quiet", "central", "window"],
        attributes: { partySize: 2, time: "20:30", table: "window" },
      },
      {
        id: "prado-counter-1900",
        offering: "Counter seats for two · 19:00",
        estimatedMarketPriceCents: 8800,
        floorPriceCents: 7200,
        quality: 88,
        marketHeat: 0.5,
        tags: ["seasonal", "central", "early", "counter"],
        attributes: { partySize: 2, time: "19:00", table: "counter" },
      },
    ],
  },
  {
    id: "taberna-lx",
    name: "Taberna LX",
    category: "dinner",
    privateSalt: "taberna-v2",
    inventory: [
      {
        id: "taberna-table-2030",
        offering: "Portuguese dinner table for two · 20:30",
        estimatedMarketPriceCents: 8200,
        floorPriceCents: 6900,
        quality: 87,
        marketHeat: 0.66,
        tags: ["local", "lively", "traditional", "central"],
        attributes: { partySize: 2, time: "20:30", table: "standard" },
      },
    ],
  },
  {
    id: "miradouro-table",
    name: "Miradouro Table",
    category: "dinner",
    privateSalt: "miradouro-v2",
    inventory: [
      {
        id: "miradouro-sunset-1930",
        offering: "Sunset tasting table for two · 19:30",
        estimatedMarketPriceCents: 12800,
        floorPriceCents: 10800,
        quality: 94,
        marketHeat: 0.92,
        tags: ["romantic", "view", "sunset", "tasting-menu"],
        attributes: { partySize: 2, time: "19:30", table: "terrace" },
      },
    ],
  },
  {
    id: "lisbon-cab",
    name: "Lisbon Cab Co.",
    category: "transport",
    privateSalt: "cab-v2",
    inventory: [
      {
        id: "cab-two-transfers",
        offering: "Two private transfers within central Lisbon",
        estimatedMarketPriceCents: 2800,
        floorPriceCents: 2200,
        quality: 85,
        marketHeat: 0.48,
        tags: ["private", "door-to-door", "evening"],
        attributes: { rides: 2, vehicle: "sedan" },
      },
    ],
  },
  {
    id: "eco-ride",
    name: "Eco Ride Lisboa",
    category: "transport",
    privateSalt: "eco-v2",
    inventory: [
      {
        id: "eco-evening-credit",
        offering: "Electric evening ride credit",
        estimatedMarketPriceCents: 2200,
        floorPriceCents: 1700,
        quality: 82,
        marketHeat: 0.4,
        tags: ["electric", "flexible", "evening"],
        attributes: { rides: 2, vehicle: "electric" },
      },
    ],
  },
  {
    id: "tejo-sunset",
    name: "Tejo Sunset",
    category: "experience",
    privateSalt: "tejo-v2",
    inventory: [
      {
        id: "tejo-deck-two",
        offering: "Two-person sunset river cruise · upper deck",
        estimatedMarketPriceCents: 7600,
        floorPriceCents: 6300,
        quality: 91,
        marketHeat: 0.79,
        tags: ["romantic", "sunset", "river", "two-seats"],
        attributes: { partySize: 2, section: "upper-deck" },
      },
    ],
  },
  {
    id: "tile-workshop",
    name: "Azulejo Atelier",
    category: "experience",
    privateSalt: "azulejo-v2",
    inventory: [
      {
        id: "tile-private-two",
        offering: "Private tile-painting session for two",
        estimatedMarketPriceCents: 6800,
        floorPriceCents: 5600,
        quality: 88,
        marketHeat: 0.52,
        tags: ["creative", "private", "local", "two-seats"],
        attributes: { partySize: 2, durationMinutes: 90 },
      },
    ],
  },
];

export function toPublicListing(
  seller: Seller,
  item: Seller["inventory"][number],
): PublicListing {
  return {
    id: item.id,
    sellerId: seller.id,
    sellerName: seller.name,
    category: seller.category,
    offering: item.offering,
    estimatedMarketPriceCents: item.estimatedMarketPriceCents,
    quality: item.quality,
    tags: [...item.tags],
    attributes: structuredClone(item.attributes),
  };
}

export function publicCatalogForPlanner(): PublicListing[] {
  return MOCK_SELLERS.flatMap((seller) =>
    seller.inventory.map((item) => toPublicListing(seller, item)),
  );
}
